version: 2
jobs:
    build:
        working_directory: ~/mage-template
        docker:
            - image: circleci/node:8.12.0
        steps:
            - checkout
            - run:
                name: install npm
                command: 'sudo npm install -g npm@latest'
            - run:
                name: install mage template
                command: |
                    cd project/
                    npm install
                    cd ..
            - run:
                name: create build folder
                command: 'mkdir build'
            - run:
                name: zip project
                command: 'tar -czvf build/project.template.tgz ./project/'
            - run:
                name: zip scene
                command: 'tar -czvf build/scene.template.tgz ./scene/'
            - run:
                name: check build folder
                command: 'ls -larch build'
            - persist_to_workspace:
                  root: build
                  # Must be relative path from root
                  paths:
                      - project.template.tgz
                      - scene.template.tgz

    publish_to_s3:
        docker:
            - image: circleci/python:latest
        steps:
            - attach_workspace:
                at: build
            - run:
                name: check content
                command: ls -larch
            - run:
                name: install awscli
                command: 'sudo pip install awscli'
            - run:
                name: publish to s3 bucket
                command: |
                    aws s3 sync build s3://${S3_BUCKET} --delete

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - publish_to_s3:
                  requires:
                      - build
